name: Generate Vimdoc
on:
  push:
    branches: [main]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.DOCS_GITHUB_TOKEN }}

      - name: Generate Vimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: wmc.nvim
          version: "Neovim >= 0.11.0"
          treesitter: true

      - name: Persist Generated Vimdoc
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(docs): update vimdoc [skip ci]"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
